### ISSUE TITLE
gojs: resolve or explain remaining os package failures

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1222]
Before extracting a file system interface, we should know why any remaining failures exist on the standard go compiler.

There are currently 23 tests that don't pass still, some might be legitimate as they aren't covered in tests such as wasi-testsuite.
```bash
$ GOARCH=wasm GOOS=js go test -c -o os.wasm os
$ wazero run -mount=/usr/local/go/src/os:/:ro -mount=/tmp:/tmp -mount=/etc:/etc:ro -mount=/usr:/usr:ro -mount=/dev:/dev:ro os.wasm | grep '^--- FAIL'

--- FAIL: TestStatError (0.00s)
--- FAIL: TestStatSymlinkLoop (0.00s)
--- FAIL: TestHardLink (0.00s)
--- FAIL: TestSymlink (0.00s)
--- FAIL: TestLongSymlink (0.00s)
--- FAIL: TestRename (0.00s)
--- FAIL: TestRenameOverwriteDest (0.00s)
--- FAIL: TestRenameNotExisting (0.00s)
--- FAIL: TestRenameCaseDifference (0.00s)
--- FAIL: TestFileChdir (0.00s)
--- FAIL: TestOpenError (0.00s)
--- FAIL: TestWriteAtInAppendMode (0.00s)
--- FAIL: TestAppend (0.00s)
--- FAIL: TestSameFile (0.00s)
--- FAIL: TestDevNullFile (0.00s)
--- FAIL: TestStatRelativeSymlink (0.00s)
--- FAIL: TestDirFSRootDir (0.00s)
--- FAIL: TestMkdirStickyUmask (0.00s)
--- FAIL: TestMkdirAllWithSymlink (0.00s)
--- FAIL: TestMkdirAllAtSlash (0.00s)
--- FAIL: TestDirAndSymlinkStats (0.01s)
--- FAIL: TestFileAndSymlinkStats (0.01s)
--- FAIL: TestSymlinkWithTrailingSlash (0.00s)
```

**Comment by codefromthecrypt** [comment]
currently down to 12. There are some nuance in the args to pass. For example, we shouldn't mask any root mounts like /etc as read-only as that affects errors and causes some to fail for a different reason.

```bash
$ wazero run -mount=/usr/local/go/src/os:/:ro -mount=/tmp:/tmp -mount=/etc:/etc -mount=/usr:/usr -mount=/dev:/dev os.wasm |grep '^--- FAIL'
--- FAIL: TestSymlink (0.00s)
--- FAIL: TestLongSymlink (0.00s)
--- FAIL: TestRenameCaseDifference (0.01s)
--- FAIL: TestStatRelativeSymlink (0.00s)
--- FAIL: TestLongPath (0.04s)
--- FAIL: TestDirFSRootDir (0.00s)
--- FAIL: TestMkdirStickyUmask (0.00s)
--- FAIL: TestMkdirAllWithSymlink (0.00s)
--- FAIL: TestMkdirAllAtSlash (0.00s)
--- FAIL: TestDirAndSymlinkStats (0.01s)
--- FAIL: TestFileAndSymlinkStats (0.00s)
--- FAIL: TestSymlinkWithTrailingSlash (0.00s)
```

**Comment by codefromthecrypt** [comment]
TestOpenFileLimit suspiciously hits too many open files at FD=253

```bash
wazero run -hostlogging=proc,filesystem -mount=/:/ --experimental-workdir=$(go env GOROOT)/src/os os.wasm -test.run '^TestOpenFileLimit$' 
--snip--
==> go.syscall/js.valueCall(fs.fstat(fd=252))
<== (err=<nil>,stat={isDir=false,mode=-rw-r--r--,size=1200,mtimeMs=1677867587000})
==> go.syscall/js.valueCall(process.cwd())
<== (cwd=/Users/adrian/.gimme/versions/go1.20.2.darwin.arm64/src/os)
==> go.syscall/js.valueCall(fs.open(path=rlimit.go,flags=,perm=----------))
<== (err=<nil>,fd=253)
==> go.syscall/js.valueCall(fs.fstat(fd=253))
<== (err=<nil>,stat={isDir=false,mode=-rw-r--r--,size=1200,mtimeMs=1677867587000})
==> go.syscall/js.valueCall(process.cwd())
<== (cwd=/Users/adrian/.gimme/versions/go1.20.2.darwin.arm64/src/os)
==> go.syscall/js.valueCall(fs.open(path=rlimit.go,flags=,perm=----------))
<== (err=too many open files,fd=0)
```

**Comment by evacchi** [comment]
> TestOpenFileLimit suspiciously hits too many open files at FD=253

works for me? 🤔 

```
...
==> go.syscall/js.valueCall(fs.close(fd=1203))
<== (err=<nil>,ok=true)
PASS
==> go.runtime.wasmExit(code=0)
<==
```

**Comment by codefromthecrypt** [comment]
| TestOpenFileLimit suspiciously hits too many open files at FD=253

ok so something on my workstation maybe. I'll look deeper

**Comment by codefromthecrypt** [comment]
after #1235 windows isn't as bad as I thought it would be, especially if go doesn't test on GOOS=js windows.

```bash
$ wasm=$PWD/os.wasm; (cd $(go env GOROOT)/src/os; wazero run -mount=c:\:/ -mount=$LOCALAPPDATA/Temp:/tmp --experimental-workdir-inherit=true $wasm)
--- FAIL: TestErrIsNotExist (0.03s)
    error_test.go:39: stat .: No such file or directory
--- FAIL: TestStat (0.00s)
    os_test.go:178: stat failed: stat /etc/group: No such file or directory
--- FAIL: TestStatError (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestStatSymlinkLoop (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestFstat (0.00s)
    os_test.go:252: open failed: open /etc/group: No such file or directory
--- FAIL: TestLstat (0.00s)
    os_test.go:272: lstat failed: lstat /etc/group: No such file or directory
--- FAIL: TestRead0 (0.00s)
    os_test.go:290: open failed: open /etc/group: No such file or directory
--- FAIL: TestReadClosed (0.01s)
    os_test.go:311: open failed: open /etc/group: No such file or directory
--- FAIL: TestFileReaddirnames (0.00s)
    os_test.go:327: open "." failed: open .: No such file or directory
--- FAIL: TestFileReaddir (0.00s)
    os_test.go:360: open "." failed: open .: No such file or directory
--- FAIL: TestFileReadDir (0.00s)
    os_test.go:393: open "." failed: open .: No such file or directory
--- FAIL: TestReaddirnamesOneAtATime (0.00s)
    os_test.go:608: open "/usr/bin" failed: open /usr/bin: No such file or directory
--- FAIL: TestHardLink (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestSymlink (0.01s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestLongSymlink (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestRename (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestRenameOverwriteDest (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestRenameFailed (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestRenameNotExisting (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestRenameToDirFailed (0.00s)
    os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestRenameCaseDifference (0.01s)
    --- FAIL: TestRenameCaseDifference/dir (0.00s)
        os_test.go:876: chtmpdir: stat .: No such file or directory
    --- FAIL: TestRenameCaseDifference/file (0.00s)
        os_test.go:876: chtmpdir: stat .: No such file or directory
--- FAIL: TestChmod (0.02s)
    os_test.go:1216: Stat "/tmp/_Go_TestChmod1755735446": mode 0444 want 0456
    os_test.go:1216: Stat "/tmp/_Go_TestChmod1755735446": mode 0444 want 0123
--- FAIL: TestFileChdir (0.00s)
    os_test.go:1376: Getwd: stat .: No such file or directory
--- FAIL: TestChdirAndGetwd (0.00s)
    os_test.go:1410: Open .: open .: No such file or directory
--- FAIL: TestProgWideChdir (0.00s)
    os_test.go:1515: Getwd: stat .: No such file or directory
panic: Fail in goroutine after TestProgWideChdir has completed

goroutine 64 [running]:
testing.(*common).Fail(0x56e340)
        C:/Users/fernc/.gimme/versions/go1.20.2.windows.amd64/src/testing/testing.go:933 +0xf
testing.(*common).Errorf(0x56e340, {0x4d251, 0x19}, {0x439fa8, 0x2, 0x2})
        C:/Users/fernc/.gimme/versions/go1.20.2.windows.amd64/src/testing/testing.go:1050 +0xe
os_test.TestProgWideChdir.func1(0x9)
        C:/Users/fernc/.gimme/versions/go1.20.2.windows.amd64/src/os/os_test.go:1505 +0x10
created by os_test.TestProgWideChdir
        C:/Users/fernc/.gimme/versions/go1.20.2.windows.amd64/src/os/os_test.go:1487 +0x5
error instantiating wasm binary: runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
        go.runtime.nanotime1(i32)
        .runtime.nanotime1(i32) i32
        .runtime.checkTimeouts(i32) i32
        .runtime.gopark(i32) i32
        .runtime.chanrecv(i32) i32
        .runtime.chanrecv1(i32) i32
        .syscall.fsCall(i32) i32
        .syscall.Open(i32) i32
        .os.openFileNolog(i32) i32
        .os.OpenFile(i32) i32
        .os.CreateTemp(i32) i32
        .os_test.newFile(i32) i32
        .wasm_pc_f_loop()
        .wasm_export_run(i32,i32)

```

**Comment by codefromthecrypt** [comment]
update: everything passes on linux and darwin.

There's more triage to do on windows, some of it is because when run in wasm, runtime.GOOS returns "js" not "windows", and the latter skips some tests. However, there look to be a couple legit ones to get through prior to 1.0

```bash
$ wasm=$PWD/os.wasm; (cd $(go env GOROOT)/src/os; wazero run -mount=c:\:/ -env=GOHOSTOS=windows -mount=$LOCALAPPDATA/Temp:/tmp $wasm)  --- FAIL: TestStat (0.00s)
    os_test.go:178: stat failed: stat /etc/group: No such file or directory
--- FAIL: TestStatError (0.02s)
    os_test.go:210: symlink no-such-file symlink: not implemented on js
--- FAIL: TestStatSymlinkLoop (0.06s)
    os_test.go:232: symlink x y: not implemented on js
--- FAIL: TestFstat (0.00s)
    os_test.go:252: open failed: open /etc/group: No such file or directory
--- FAIL: TestLstat (0.00s)
    os_test.go:272: lstat failed: lstat /etc/group: No such file or directory
--- FAIL: TestRead0 (0.00s)
    os_test.go:290: open failed: open /etc/group: No such file or directory
--- FAIL: TestReadClosed (0.00s)
    os_test.go:311: open failed: open /etc/group: No such file or directory
--- FAIL: TestFileReaddirnames (0.02s)
    os_test.go:327: open "/etc" failed: open /etc: No such file or directory
--- FAIL: TestFileReaddir (0.22s)
    os_test.go:360: open "/etc" failed: open /etc: No such file or directory
--- FAIL: TestFileReadDir (0.20s)
    os_test.go:393: open "/etc" failed: open /etc: No such file or directory
--- FAIL: TestReaddirnamesOneAtATime (0.00s)
    os_test.go:608: open "/usr/bin" failed: open /usr/bin: No such file or directory
--- FAIL: TestSymlink (0.02s)
    os_test.go:907: Symlink("symlinktestto", "symlinktestfrom") failed: symlink symlinktestto symlinktestfrom: not implemented on js
--- FAIL: TestLongSymlink (0.01s)
    os_test.go:964: symlink "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", "longsymlinktestfrom" failed: symlink 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef longsymlinktestfrom: not implemented on js
--- FAIL: TestRenameCaseDifference (0.05s)
    --- FAIL: TestRenameCaseDifference/dir (0.02s)
        os_test.go:1128: unexpected error when renaming from "renameFROM" to "RENAMEfrom": rename renameFROM RENAMEfrom: No such file or directory
--- FAIL: TestChmod (0.01s)
    os_test.go:1216: Stat "/tmp/_Go_TestChmod3769272958": mode 0444 want 0456
    os_test.go:1216: Stat "/tmp/_Go_TestChmod3769272958": mode 0444 want 0123
--- FAIL: TestChdirAndGetwd (0.01s)
    os_test.go:1465: Chdir /usr/bin: chdir /usr/bin: No such file or directory
--- FAIL: TestOpenError (0.00s)
    os_test.go:1679: Open("/etc", 1) = _, "No such file or directory"; want "Is a directory"
    os_test.go:1679: Open("/etc/group/no-such-file", 1) = _, "No such file or directory"; want "Not a directory"
--- FAIL: TestDevNullFile (0.00s)
    os_test.go:2036: Open(/dev/null): open /dev/null: No such file or directory
--- FAIL: TestStatRelativeSymlink (0.05s)
    os_test.go:2171: symlink target /tmp/TestStatRelativeSymlink1241735806/001/link: not implemented on js
--- FAIL: TestLongPath (0.83s)
    --- FAIL: TestLongPath/length=247 (0.14s)
        os_test.go:2268: Stat("/tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir345x/symlink.txt") failed: stat /tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir345x/symlink.txt: No such file or directory
    --- FAIL: TestLongPath/length=248 (0.04s)
        os_test.go:2268: Stat("/tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456x/symlink.txt") failed: stat /tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456x/symlink.txt: No such file or directory
    --- FAIL: TestLongPath/length=249 (0.04s)
        os_test.go:2268: Stat("/tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir34567x/symlink.txt") failed: stat /tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir34567x/symlink.txt: No such file or directory
    --- FAIL: TestLongPath/length=400 (0.10s)
        os_test.go:2268: Stat("/tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir34x/symlink.txt") failed: stat /tmp/_Go_TestLongPath830187276/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir3456789/dir34x/symlink.txt: No such file or directory
--- FAIL: TestDoubleCloseError (0.00s)
    os_test.go:2530: open /etc/group: No such file or directory
--- FAIL: TestDirFS (0.15s)
    os_test.go:2707: TestFS found errors:
        dir/x: Open(dir\x) succeeded, want error
        dir/x: Open(dir\x) succeeded, want error
--- FAIL: TestDirFSRootDir (0.00s)
    os_test.go:2752: stat /testdata/dirfs/a: invalid argument
--- FAIL: TestDirFSPathsValid (0.09s)
    os_test.go:2781: open /tmp/TestDirFSPathsValid3060872330/001/e:xperi\ment.txt: I/O error
--- FAIL: TestChown (0.01s)
    os_unix_test.go:58: gid: 0
    os_unix_test.go:60: chown /tmp/_Go_TestChown1296188498 -1 0: chown /tmp/_Go_TestChown1296188498: I/O error
--- FAIL: TestFileChown (0.02s)
    os_unix_test.go:101: gid: 0
    os_unix_test.go:103: fchown /tmp/_Go_TestFileChown2136755205 -1 0: chown /tmp/_Go_TestFileChown2136755205: not implemented on js
--- FAIL: TestLchown (0.03s)
    os_unix_test.go:153: gid: 0
    os_unix_test.go:158: lchown /tmp/_Go_TestLchown10340531862 -1 0: lchown /tmp/_Go_TestLchown10340531862: I/O error
--- FAIL: TestMkdirStickyUmask (0.04s)
    os_unix_test.go:231: unexpected mode drwxrwxrwx
--- FAIL: TestMkdirAllWithSymlink (0.05s)
    path_test.go:88: Symlink /tmp/TestMkdirAllWithSymlink1894828190/001/link: symlink dir /tmp/TestMkdirAllWithSymlink1894828190/001/link: not implemented on js
--- FAIL: TestDirAndSymlinkStats (0.06s)
    stat_test.go:21: stat /tmp/TestDirAndSymlinkStats189990065/001/link: No such file or directory
    stat_test.go:168: stat /tmp/TestDirAndSymlinkStats189990065/001/link: No such file or directory
    stat_test.go:21: stat /tmp/TestDirAndSymlinkStats189990065/001/linklink: No such file or directory
    stat_test.go:168: stat /tmp/TestDirAndSymlinkStats189990065/001/linklink: No such file or directory
--- FAIL: TestFileAndSymlinkStats (0.08s)
    stat_test.go:21: stat /tmp/TestFileAndSymlinkStats2562106440/001/link: No such file or directory
    stat_test.go:168: stat /tmp/TestFileAndSymlinkStats2562106440/001/link: No such file or directory
    stat_test.go:21: stat /tmp/TestFileAndSymlinkStats2562106440/001/linklink: No such file or directory
    stat_test.go:168: stat /tmp/TestFileAndSymlinkStats2562106440/001/linklink: No such file or directory
--- FAIL: TestSymlinkWithTrailingSlash (0.07s)
    stat_test.go:21: stat /tmp/TestSymlinkWithTrailingSlash4177944932/001/link/: No such file or directory
    stat_test.go:263: stat /tmp/TestSymlinkWithTrailingSlash4177944932/001/link/: No such file or directory
FAIL

```

**Comment by mathetake** [comment]
is the official Go repo passing these tests with node on windows?

**Comment by codefromthecrypt** [comment]
iirc it isn't running windows tests at all. I think at least one of these tests are legit though, as we should sort it regardless. There are some edge cases about mixing path separators which @evacchi has fixed a couple times :D

**Comment by codefromthecrypt** [comment]
yeah looks like wasm is only tested on linux and one arch https://build.golang.org

**Comment by mathetake** [comment]
I see.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/13513977/225512240-12f33bbb-55ab-414c-a561-4d4eccc52c37.png">

**Comment by mathetake** [comment]
I think we could just note it and close this issue once the legit one is fixed.

**Comment by codefromthecrypt** [comment]
yep that would satisfy "resolve or explain" fairly!

**Comment by codefromthecrypt** [comment]
this is antique because gojs is being replaced with wasip1 (so it is in maintenance mode now).
