### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference (recovered by wazero)

### ISSUE THREAD

**Issue by k33g** [tetratelabs/wazero#1399]
**Describe the bug**
When calling a host function from a wasm module, I get this error:
(I can pass messages from WASM module to Host, but I cannot pass messages from the Host to the WASM module)

```
👋 from the module: Hello Bob Morane
message from WASM: this is a message
2023/04/24 23:53:54 runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
        env.hostTalk(i32,i32,i32,i32) i32
        .hello(i32,i32) i64
panic: runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
        env.hostTalk(i32,i32,i32,i32) i32
        .hello(i32,i32) i64


goroutine 1 [running]:
log.Panicln({0x40001edeb0?, 0x1cb290?, 0x40000a4000?})
        /usr/local/go/src/log/log.go:398 +0x60
main.main()
        /home/ubuntu/wazero-step-by-step/chapter-04/host/main.go:167 +0x564
exit status 2
```

**To Reproduce**
- host function: https://github.com/wasm-university/wazero-step-by-step/blob/main/chapter-04/host/main.go#L32
- wasm module (call of the host function): https://github.com/wasm-university/wazero-step-by-step/blob/main/chapter-04/function/hello.go#L67

**Expected behavior**

- I can pass messages from WASM module to Host, and I can pass messages from the Host to the WASM module

**Environment (please complete the relevant information):**
- Go version: 1.20
- wazero Version: 1.0.3
- Host architecture: arm64
- Runtime mode: interpreter

**Comment by mathetake** [comment]
`allocateBuffer` is not existent in your guest and you've tried to execute the nil function here https://github.com/wasm-university/wazero-step-by-step/blob/main/chapter-04/host/main.go#L50

**Comment by mathetake** [comment]
ps we are aware of this difficulty in debugging the host function panics due to the TODO here: https://github.com/tetratelabs/wazero/blob/main/internal/wasmdebug/debug.go#L134 

we are likely to solve it shortly, so stay tuned!

**Comment by mathetake** [comment]
with #1401  you can see the following error which verifies my analysis above!

```
2023/04/25 10:35:16 runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
        env.hostTalk(i32,i32,i32,i32) i32
        .hello(i32,i32) i64

Go runtime stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/tetratelabs/wazero/internal/wasmdebug.(*stackTrace).FromRecovered(0x140001e78d0?, {0x100285760?, 0x100396360?})
        /Users/mathetake/wazero/internal/wasmdebug/debug.go:139 +0xc4
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).deferredOnCall(0x14000178900, {0x100285760, 0x100396360})
        /Users/mathetake/wazero/internal/engine/compiler/engine.go:803 +0x25c
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call.func1()
        /Users/mathetake/wazero/internal/engine/compiler/engine.go:691 +0x4c
panic({0x100285760, 0x100396360})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
main.glob..func2({0x1002a8e80, 0x14000112000}, {0x1002aa528, 0x140001786c0}, {0x14000249048, 0x4, 0x140001e7c01?})
        /Users/mathetake/wazero-step-by-step/chapter-04/host/main.go:50 +0x170
github.com/tetratelabs/wazero/api.GoModuleFunc.Call(0x1078d8038?, {0x1002a8e80?, 0x14000112000?}, {0x1002aa528?, 0x140001786c0?}, {0x14000249048?, 0x140001e7c88?, 0x1000fb1e4?})
        /Users/mathetake/wazero/api/wasm.go:411 +0x54
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction(0x14000178900, {0x1002a8e80?, 0x14000112000?}, 0x1003a4300?)
        /Users/mathetake/wazero/internal/engine/compiler/engine.go:953 +0x158
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call(0x14000178900, {0x1002a8e80, 0x14000112000}, {0x14000112af0?, 0x2, 0x1b68?})
        /Users/mathetake/wazero/internal/engine/compiler/engine.go:705 +0x2b4
main.main()
        /Users/mathetake/wazero-step-by-step/chapter-04/host/main.go:165 +0x534

```

**Comment by k33g** [comment]
🤦🏻 I'm so s...! I was using some parts of the code of my Capsule project, and I forgot to take the `allocateBuffer` function.
@
I'm very sorry about that. And thank you very much for your help @mathetake 🙏

**Comment by mathetake** [comment]
no sorry needed! 👍
