### ISSUE TITLE
Compiler benchmarks panic due to a segmentation fault

### ISSUE THREAD

**Issue by achille-roussel** [tetratelabs/wazero#1464]
**Describe the bug**

Running the `BenchmarkCompiler_compileMemoryCopy` benchmarks panic due to a segmentation fault.

**To Reproduce**

```
$ go test -run '^$' -bench BenchmarkCompiler_compileMemoryCopy -benchmem -count 10 ./internal/engine/compiler
```

**Expected behavior**

The benchmark should run to completion.

**Screenshots**

```
unexpected fault address 0x140000f4000
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x140000f4000 pc=0x140000f4000]

goroutine 8 [running]:
runtime.throw({0x102e09f2b?, 0x174?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x140000d3c70 sp=0x140000d3c40 pc=0x102bf3d80
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:834 +0x10c fp=0x140000d3cb0 sp=0x140000d3c70 pc=0x102c0a92c
github.com/tetratelabs/wazero/internal/engine/compiler.(*compilerEnv).execBench(0x1400000c090, 0x1400006cc80, {0x140000f4000, 0x174, 0x14000033d78?})
	/Users/achilleroussel/go/src/github.com/tetratelabs/wazero/internal/engine/compiler/compiler_bench_test.go:114 +0x6c fp=0x140000d3d00 sp=0x140000d3cc0 pc=0x102da9acc
github.com/tetratelabs/wazero/internal/engine/compiler.BenchmarkCompiler_compileMemoryCopy.func1(0x1400006cc80)
	/Users/achilleroussel/go/src/github.com/tetratelabs/wazero/internal/engine/compiler/compiler_bench_test.go:53 +0x594 fp=0x140000d3f10 sp=0x140000d3d00 pc=0x102da9224
testing.(*B).runN(0x1400006cc80, 0x1)
	/usr/local/go/src/testing/benchmark.go:193 +0x128 fp=0x140000d3f90 sp=0x140000d3f10 pc=0x102c82478
testing.(*B).run1.func1()
	/usr/local/go/src/testing/benchmark.go:233 +0x50 fp=0x140000d3fd0 sp=0x140000d3f90 pc=0x102c82a90
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000d3fd0 sp=0x140000d3fd0 pc=0x102c26e34
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:226 +0x8c
```

**Environment**
- Go version: 1.20
- wazero Version: 4ceef7b24533725f2ef0d406c3baf633d99eca32
- Host architecture: amd64, arm64
- Runtime mode: compiler

**Additional context**

I tested on both linux/amd64 and darwin/arm64, both panicked in the same way.

**Comment by mathetake** [comment]
I think this is because this bench hasn't been run on CI accidentally

**Comment by evacchi** [comment]
looking into this. Essentially, the panic is due to codeSegment not being mmap'd; so this is enough:

```
func (j *compilerEnv) execBench(b *testing.B, codeSegment []byte) {
	executable := requireExecutable(codeSegment)
	b.StartTimer()
```

(unless you want to measure the mmap overhead too)

once this is done, there is another panic due to the change to how `functionDefintition`s are now loaded; looking into that too. Will open a PR.

as for running this in the CI, shall we add this to the Makefile?

```
bench:
	@go test -run=NONE -benchmem -bench=. ./internal/engine/compiler/...
	@go test -run=NONE -benchmem -bench=. ./internal/integration_test/bench/...
	@go test -benchmem -bench=. ./internal/integration_test/vs/... $(ensureCompilerFastest)

.PHONY: bench.check
bench.check:
	@go build ./internal/engine/compiler/...
	@go build ./internal/integration_test/bench/...
	# ... etc
```

**Comment by codefromthecrypt** [comment]
we run `make bench.check`, not `make bench` in CI, I thought because the latter took too long. You can raise a PR to see how long it does, maybe it isn't as long as fuzzing..
