### ISSUE TITLE
Flakey test: TestStore_hammer_close

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1476]
TestStore_hammer_close has flaked on windows. I wonder if it is using too much memory, as the line leading to failure is nothing special.

```
goroutine 2076 [running]:
runtime.systemstack_switch()
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/runtime/asm_amd64.s:463 fp=0xc0001a3860 sp=0xc0001a3858 pc=0x4b13e0
runtime.(*mheap).alloc(0x10000?, 0x8?, 0x1?)
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/runtime/mheap.go:955 +0x65 fp=0xc0001a38a8 sp=0xc0001a3860 pc=0x46d005
runtime.(*mcache).allocLarge(0xc0000a22d8?, 0x10000, 0x1)
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/runtime/mcache.go:234 +0x85 fp=0xc0001a38f0 sp=0xc0001a38a8 pc=0x45c605
runtime.mallocgc(0x10000, 0x6dfba0, 0x1)
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/runtime/malloc.go:1053 +0x52f fp=0xc0001a3[97](https://github.com/tetratelabs/wazero/actions/runs/4988140286/jobs/8930599574#step:4:98)0 sp=0xc0001a38f0 pc=0x45312f
runtime.makeslice(0xc02b57f700?, 0xc00019a340?, 0x0?)
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/runtime/slice.go:103 +0x52 fp=0xc0001a39[98](https://github.com/tetratelabs/wazero/actions/runs/4988140286/jobs/8930599574#step:4:99) sp=0xc0001a3970 pc=0x495b52
github.com/tetratelabs/wazero/internal/wasm.NewMemoryInstance(...)
	D:/a/wazero/wazero/internal/wasm/memory.go:59
github.com/tetratelabs/wazero/internal/wasm.(*ModuleInstance).buildMemory(...)
	D:/a/wazero/wazero/internal/wasm/module.go:637
github.com/tetratelabs/wazero/internal/wasm.(*Store).instantiate(0xc000053800, {0x7d0d98, 0xc0000729c0}, 0xc00019a340, {0xc02b4faa6c, 0x4}, 0xc02b5f2f00, {0xc02b4faaac, 0x1, 0x1})
	D:/a/wazero/wazero/internal/wasm/store.go:345 +0x5d8 fp=0xc0001a3b08 sp=0xc0001a3[99](https://github.com/tetratelabs/wazero/actions/runs/4988140286/jobs/8930599574#step:4:100)8 pc=0x60f6b8
github.com/tetratelabs/wazero/internal/wasm.(*Store).Instantiate(0x0?, {0x7d0d98, 0xc0000729c0}, 0x0?, {0xc02b4faa6c, 0x4}, 0x56ac0b?, {0xc02b4faaac, 0x1, 0x1})
	D:/a/wazero/wazero/internal/wasm/store.go:304 +0xbf fp=0xc0001a3b98 sp=0xc0001a3b08 pc=0x60efdf
github.com/tetratelabs/wazero/internal/wasm.TestStore_hammer_close(0xc00019a000)
	D:/a/wazero/wazero/internal/wasm/store_test.go:277 +0xec6 fp=0xc0001a3ea8 sp=0xc0001a3b98 pc=0x681b66
testing.tRunner(0xc00019a000, 0x73c0c0)
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/testing/testing.go:1576 +0x217 fp=0xc0001a3fb0 sp=0xc0001a3ea8 pc=0x56add7
testing.(*T).Run.func1()
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/testing/testing.go:1629 +0x48 fp=0xc0001a3fe0 sp=0xc0001a3fb0 pc=0x56c8e8
runtime.goexit()
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001a3fe8 sp=0xc0001a3fe0 pc=0x4b36e1
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.4/x64/src/testing/testing.go:1629 +0x806
```

**Comment by evacchi** [comment]
I suspect this is the same tests that failed on `main` even though there is no trace https://github.com/tetratelabs/wazero/actions/runs/4989489321/jobs/8933478739
