### ISSUE TITLE
flakey threads_test.go

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1485]
We're getting timeouts occasionally on the new threads hammer test, not sure if go version specific. cc @anuraaga 

https://github.com/tetratelabs/wazero/actions/runs/5025075730/jobs/9011586240
```
panic: test timed out after 10m0s

goroutine 527 [running]:
testing.(*M).startAlarm.func1()
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:2029 +0xbb
created by time.goFunc
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00012c000, {0x14605e6, 0x16}, 0x1474140)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1487 +0x750
testing.runTests.func1(0x0?)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1839 +0x9a
testing.tRunner(0xc00012c000, 0xc000115ba0)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x214
testing.runTests(0xc0000c4aa0?, {0x16a5c20, 0x6, 0x6}, {0x40?, 0x21af598?, 0x16b40a0?})
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1837 +0x7e5
testing.(*M).Run(0xc0000c4aa0)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1719 +0xa72
main.main()
	_testmain.go:57 +0x2e5

goroutine 522 [chan receive, 9 minutes]:
github.com/tetratelabs/wazero/internal/testing/hammer.(*hammer).Run(0xc000357d58, 0xc000204420, 0x14741a0)
	/Users/runner/work/wazero/wazero/internal/testing/hammer/hammer.go:106 +0x3f9
github.com/tetratelabs/wazero/internal/integration_test/engine.incrementGuardedByMutex.func1(0xc0002ac4e0)
	/Users/runner/work/wazero/wazero/internal/integration_test/engine/threads_test.go:95 +0x2b5
testing.tRunner(0xc0002ac4e0, 0xc0002040c0)
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/Users/runner/hostedtoolcache/go/1.18.10/x64/src/testing/testing.go:1486 +0x725

goroutine 524 [chan receive, 9 minutes]:
github.com/tetratelabs/wazero/internal/wasm.(*MemoryInstance).Wait(0xc000207260, 0x0?, 0xffffffffffffffff)
	/Users/runner/work/wazero/wazero/internal/wasm/memory.go:326 +0x8da
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callNativeFunc(0xc000149c80, {0x14e5918, 0xc00009d740}, 0x1?, 0xc0001286a0)
	/Users/runner/work/wazero/wazero/internal/engine/interpreter/interpreter.go:3934 +0x231f3
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callFunction(0x13fe340?, {0x14e5918, 0xc00009d740}, 0xffffffffffffffff?, 0xc0001286a0)
	/Users/runner/work/wazero/wazero/internal/engine/interpreter/interpreter.go:602 +0x11e
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callNativeFunc(0xc000149c80, {0x14e5918, 0xc00009d740}, 0x320000000000003a?, 0xc0001286e0)
	/Users/runner/work/wazero/wazero/internal/engine/interpreter/interpreter.go:679 +0x945
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).callFunction(0xc000270c98?, {0x14e5918, 0xc00009d740}, 0x10ae505?, 0xc0001286e0)
	/Users/runner/work/wazero/wazero/internal/engine/interpreter/interpreter.go:602 +0x11e
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).call(0xc000149c80, {0x14e5918, 0xc00009d740}, {0x0, 0x0, 0x1b?}, {0x0, 0x0, 0x0})
	/Users/runner/work/wazero/wazero/internal/engine/interpreter/interpreter.go:541 +0x3c8
github.com/tetratelabs/wazero/internal/engine/interpreter.(*callEngine).Call(0xc000149c80, {0x14e5918, 0xc00009d740}, {0x0, 0x0, 0x0})
	/Users/runner/work/wazero/wazero/internal/engine/interpreter/interpreter.go:496 +0x1ab
github.com/tetratelabs/wazero/internal/integration_test/engine.incrementGuardedByMutex.func1.1({0x1459a26?, 0x8?})
	/Users/runner/work/wazero/wazero/internal/integration_test/engine/threads_test.go:96 +0xaa
github.com/tetratelabs/wazero/internal/testing/hammer.(*hammer).Run.func1()
	/Users/runner/work/wazero/wazero/internal/testing/hammer/hammer.go:87 +0x20c
created by github.com/tetratelabs/wazero/internal/testing/hammer.(*hammer).Run
	/Users/runner/work/wazero/wazero/internal/testing/hammer/hammer.go:74 +0x17b
```

**Comment by codefromthecrypt** [comment]
not go specific https://github.com/tetratelabs/wazero/actions/runs/5030447207/jobs/9022882056
