### ISSUE TITLE
flaky test: in ExampleCoreFeaturesThreads

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#1936]
cc @anuraaga @ncruces 

https://github.com/tetratelabs/wazero/actions/runs/7617746876/job/20747441295?pr=1935
https://github.com/tetratelabs/wazero/actions/runs/7614493794/job/20736874840?pr=1926

The test causes segv occasionally 

```
unexpected fault address 0x7fa6bc2fb480
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fa6bc2fb480 pc=0x7fa6bc32c292]

goroutine 29 [running]:
runtime.throw({0x6d899d?, 0x8d53f8?})
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:1047 +0x5d fp=0xc000428cf8 sp=0xc000428cc8 pc=0x438edd
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/signal_unix.go:846 +0x2c5 fp=0xc000428d48 sp=0xc000428cf8 pc=0x44f965
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction(0xc00043e870, {0x739908, 0xc0000b2000}, 0xc00021d590?)
	/home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:1049 +0xa5 fp=0xc000428dc8 sp=0xc000428d48 pc=0x5d4bc5
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).call(0xc00043e870, {0x739908, 0xc0000b2000}, {0x0?, 0x5d33ff?, 0x0?}, {0x0, 0x0, 0x0})
	/home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:790 +0x27e fp=0xc000428e98 sp=0xc000428dc8 pc=0x5d39de
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call(0xc00043e870?, {0x739908?, 0xc0000b2000?}, {0x0?, 0x0?, 0x0?})
	/home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:742 +0x10b fp=0xc000428f10 sp=0xc000428e98 pc=0x5d370b
github.com/tetratelabs/wazero/experimental_test.ExampleCoreFeaturesThreads.func1()
	/home/runner/work/wazero/wazero/experimental/features_example_test.go:75 +0x16b fp=0xc000428fe0 sp=0xc000428f10 pc=0x63590b
runtime.goexit()
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000428fe8 sp=0xc000428fe0 pc=0x46ba41
created by github.com/tetratelabs/wazero/experimental_test.ExampleCoreFeaturesThreads
	/home/runner/work/wazero/wazero/experimental/features_example_test.go:66 +0x4cb
```

**Comment by mathetake** [comment]
still continues https://github.com/tetratelabs/wazero/actions/runs/7619637406/job/20753045828

**Comment by mathetake** [comment]
seems like all happens on Go 1.19, but I can't say if this is 1.19 specific
