### ISSUE TITLE
Flake on jit_test.go: TestAmd64Compiler_compileBrTable

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#328]
at the time, the code that failed was this line, which was nil.

```
	jitcall(
		uintptr(unsafe.Pointer(&code[0])),
		uintptr(unsafe.Pointer(j.vm)),
	)
```

It should not be nil due to jit_amd64.s
```
// jitcall(codeSegment, callEngine)
TEXT ·jitcall(SB),NOSPLIT|NOFRAME,$0-16
--snip--
```

```
--- FAIL: TestAmd64Compiler_compileBrTable (0.39s)
[18](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:18)
    --- FAIL: TestAmd64Compiler_compileBrTable/index_register=2074,tmpRegister=2064 (0.02s)
[19](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:19)
        --- FAIL: TestAmd64Compiler_compileBrTable/index_register=[20](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:20)74,tmpRegister=2064/select_last_with_five_targets (0.01s)
20
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[21](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:21)
	panic: runtime error: invalid memory address or nil pointer dereference
[22](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:22)
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x24ae066]
[23](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:23)

[24](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:24)
goroutine 862 [running]:
[25](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:25)
testing.tRunner.func1.2({0x12ae360, 0x1513370})
[26](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:26)
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1209 +0x24e
[27](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:27)
testing.tRunner.func1()
[28](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:28)
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1212 +0x218
[29](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:29)
panic({0x12ae360, 0x1513370})
[30](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:30)
	/Users/runner/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1038 +0x215
[31](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:31)
github.com/tetratelabs/wazero/internal/wasm/jit.(*jitEnv).exec(0xc00000e078, {0x24ae000, 0x1a9, 0x1a9})
[32](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:32)
	/Users/runner/work/wazero/wazero/internal/wasm/jit/jit_test.go:122 +0x20e
[33](https://github.com/tetratelabs/wazero/runs/5415751283?check_suite_focus=true#step:5:33)
github.com/tetratelabs/wazero/internal/wasm/jit.TestAmd64Compiler_compileBrTable.func1(0x1361978, 0xc00009ad80, 0x12abe40)
```

**Comment by mathetake** [comment]
So I couldn't reproduce this on my local linux so maybe mac specific one
```
<< /usr/local/go/bin/go test -run ^TestAmd64Compiler_compileBrTable$ github.com/tetratelabs/wazero/internal/wasm/jit -count=1000  
ok      github.com/tetratelabs/wazero/internal/wasm/jit 286.418s

mathetake@mathetake ~/wazero simpleiotafeature* 4m 47s
>> uname -a
Linux mathetake 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mathetake** [comment]
ok getting closer to the root cause..

**Comment by mathetake** [comment]
turns out that this is not macos specific e.g. https://github.com/tetratelabs/wazero/runs/5421897514?check_suite_focus=true
