### ISSUE TITLE
test: `TestModuleEngine_Close_Concurrent` is flaky on windows

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#377]
```
fatal error: unexpected signal during runtime execution
[18](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:18)
[signal 0xc0000005 code=0x1 addr=0x2cbf0fedd28 pc=0x8fc66a]
[19](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:19)

[20](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:20)
goroutine 22 [running]:
[21](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:21)
runtime.throw({0xbbcef2, 0x2cbf0fedd18})
[22](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:22)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/panic.go:1198 +0x76 fp=0xc0005397c0 sp=0xc000539790 pc=0x908eb6
[23](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:23)
runtime.sigpanic()
[24](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:24)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/signal_windows.go:248 +0x22b fp=0xc000539808 sp=0xc0005397c0 pc=0x91d60b
[25](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:25)
runtime.newBucket(0x1, 0x9)
[26](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:26)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/mprof.go:175 +0x6a fp=0xc000539838 sp=0xc000539808 pc=0x8fc66a
[27](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:27)
runtime.stkbucket(0x1, 0xd0, {0xc0005398e8, 0xc0005396f0, 0x20}, 0x1)
[28](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:28)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/mprof.go:240 +0x1f4 fp=0xc0005398a0 sp=0xc000539838 pc=0x8fc974
[29](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:29)
runtime.mProf_Malloc(0xc000022340, 0xd0)
[30](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:30)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/mprof.go:344 +0xb1 fp=0xc000539a10 sp=0xc0005398a0 pc=0x8fce91
[31](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:31)
runtime.profilealloc(0x2cbcbac4b0d, 0xd0, 0x8e6e2f)
[32](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:32)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/malloc.go:1270 +0x85 fp=0xc000539a48 sp=0xc000539a10 pc=0x8ddb05
[33](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:33)
runtime.mallocgc(0xd0, 0xb80120, 0x1)
[34](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:34)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/malloc.go:1149 +0x72a fp=0xc000539ac8 sp=0xc000539a48 pc=0x8dd6aa
[35](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:35)
runtime.newobject(0x8dd634)
[36](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:36)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/malloc.go:1234 +0x27 fp=0xc000539af0 sp=0xc000539ac8 pc=0x8dd987
[37](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:37)
runtime.CallersFrames(...)
[38](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:38)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/symtab.go:66
[39](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:39)
runtime.Caller(0x2)
[40](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:40)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/extern.go:203 +0x7e fp=0xc000539c00 sp=0xc000539af0 pc=0x8d9ebe
[41](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:41)
github.com/stretchr/testify/assert.CallerInfo()
[42](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:42)
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:115 +0x6c fp=0xc000539cc8 sp=0xc000539c00 pc=0xaf5fac
[43](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:43)
github.com/stretchr/testify/assert.Fail({0x2cbf0e8e2c8, 0xc00037e340}, {0xbb8ff4, 0x21}, {0x0, 0x0, 0x0})
[44](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:44)
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:246 +0x89 fp=0xc000539d98 sp=0xc000539cc8 pc=0xaf6929
[45](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:45)
github.com/stretchr/testify/assert.Error({0x2cbf0e8e2c8, 0xc00037e340}, {0x0, 0x0}, {0x0, 0x0, 0x0})
[46](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:46)
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.7.0/assert/assertions.go:1349 +0x9d fp=0xc000539de0 sp=0xc000539d98 pc=0xaf9d7d
[47](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:47)
github.com/stretchr/testify/require.Error({0xc19258, 0xc00037e340}, {0x0, 0x0}, {0x0, 0x0, 0x0})
[48](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:48)
	C:/Users/runneradmin/go/pkg/mod/github.com/stretchr/testify@v1.7.0/require/require.go:253 +0x96 fp=0xc000539e28 sp=0xc000539de0 pc=0xafb476
[49](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:49)
github.com/tetratelabs/wazero/internal/wasm/jit.TestModuleEngine_Close_Concurrent.func2(0xc00037e340)
[50](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:50)
	D:/a/wazero/wazero/internal/wasm/jit/engine_test.go:361 +0xaa7 fp=0xc000539f70 sp=0xc000539e28 pc=0xb15507
[51](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:51)
testing.tRunner(0xc00037e340, 0xc00004c780)
[52](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:52)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1259 +0x102 fp=0xc000[53](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:53)9fc0 sp=0xc000539f70 pc=0x9a9202
53
testing.(*T).Run·dwrap·21()
[54](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:54)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1306 +0x2a fp=0xc000539fe0 sp=0xc000539fc0 pc=0x9a9f0a
[55](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:55)
runtime.goexit()
[56](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:56)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000539fe8 sp=0xc000539fe0 pc=0x9396e1
[57](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:57)
created by testing.(*T).Run
[58](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:58)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1306 +0x35a
[59](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:59)

[60](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:60)
goroutine 1 [chan receive]:
[61](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:61)
testing.(*T).Run(0xc000156340, {0xbb9099, 0x93c273}, 0xbc7678)
[62](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:62)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1307 +0x375
[63](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:63)
testing.runTests.func1(0xc000156340)
[64](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:64)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1598 +0x6e
[65](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:65)
testing.tRunner(0xc000156340, 0xc000073cc8)
[66](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:66)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1259 +0x102
[67](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:67)
testing.runTests(0xc00011c100, {0xdc88e0, 0x38, 0x38}, {0x8dd634, 0x2, 0xe00080})
[68](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:68)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1596 +0x43f
[69](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:69)
testing.(*M).Run(0xc00011c100)
[70](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:70)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1504 +0x51d
[71](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:71)
github.com/tetratelabs/wazero/internal/wasm/jit.TestMain(0x10100cbcba60108)
[72](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:72)
	D:/a/wazero/wazero/internal/wasm/jit/jit_test.go:21 +0x19
[73](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:73)
main.main()
[74](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:74)
	_testmain.go:155 +0x165
[75](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:75)

[76](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:76)
goroutine 21 [chan receive]:
[77](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:77)
testing.(*T).Run(0xc00037e000, {0xbab448, 0xd8f6a0}, 0xc00004c[78](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:78)0)
78
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1307 +0x375
[79](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:79)
github.com/tetratelabs/wazero/internal/wasm/jit.TestModuleEngine_Close_Concurrent(0xc000157d40)
[80](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:80)
	D:/a/wazero/wazero/internal/wasm/jit/engine_test.go:309 +0xcfe
[81](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:81)
testing.tRunner(0xc00037e000, 0xbc7678)
[82](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:82)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1259 +0x102
[83](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:83)
created by testing.(*T).Run
[84](https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true#step:5:84)
	C:/hostedtoolcache/windows/go/1.17.7/x64/src/testing/testing.go:1306 +0x35a
```

https://github.com/tetratelabs/wazero/runs/5563644494?check_suite_focus=true
https://github.com/tetratelabs/wazero/runs/5563509947?check_suite_focus=true

I tried the following on my ubuntu (amd64) and darwin (arm64), but succeeded without issue:

```
go test -run ^TestModuleEngine_Close_Concurrent$ github.com/tetratelabs/wazero/internal/wasm/jit -cpu 2 -v -count 100000
```

**Comment by codefromthecrypt** [comment]
@wdvxdr1123 would you mind taking a look to see if you can identify why this is flakey? I don't know if there are thread-safety issues in the apis we are using, but if so we would have to add a mutex I guess. Note that the code changed a little since you last looked.

**Comment by wdvxdr1123** [comment]
https://github.com/tetratelabs/wazero/blob/f69115ac3d68f6ff8b4a2f42ec9c8b2d3c8f6658/internal/wasm/jit/mmap_windows.go#L114-L123

I think this function caused this issue. As GetLastError documented, `The last-error code is maintained on a per-thread basis. Multiple threads do not overwrite each other's last-error code.`, but go runtime can shedule any goroutine to another thread.

See:
https://github.com/golang/sys/blob/039c03cc5b867cd7b06a19ff375be5c945c80b10/windows/zsyscall_windows.go#L3105-L3112
https://github.com/golang/sys/blob/039c03cc5b867cd7b06a19ff375be5c945c80b10/windows/zsyscall_windows.go#L23-L36

Handling errno in this way may be better.

**Comment by codefromthecrypt** [comment]
I see, I think particularly we can do this and make sure we guard when e1 is zero because that being zero is why I added the code which seems to be problematic. Thanks for the advice!

**Comment by codefromthecrypt** [comment]
ok! https://github.com/tetratelabs/wazero/pull/381
