### ISSUE TITLE
flakey test: wasm3 bench

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#413]
If this happens frequently, we may have to remove it because there is no maintained go binding to wasm3

```
Run make bench.check
[7](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:7)
panic: test timed out after 10m0s
[8](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:8)

[9](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:9)
goroutine 14 [running]:
[10](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:10)
testing.(*M).startAlarm.func1()
[11](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:11)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1788 +0x8e
[12](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:12)
created by time.goFunc
[13](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:13)
	/opt/hostedtoolcache/go/1.17.7/x64/src/time/sleep.go:180 +0x31
[14](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:14)

[15](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:15)
goroutine 1 [chan receive, 9 minutes]:
[16](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:16)
testing.(*T).Run(0xc000087860, {0x12bbbb0, 0x6484b3}, 0x12d0000)
[17](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:17)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1307 +0x375
[18](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:18)
testing.runTests.func1(0xc000087860)
[19](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:19)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1598 +0x6e
[20](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:20)
testing.tRunner(0xc000087860, 0xc00010dd18)
[21](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:21)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1259 +0x102
[22](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:22)
testing.runTests(0xc000104180, {0x181a640, 0x3, 0x3}, {0x65952d, 0x12b6893, 0x18933c0})
[23](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:23)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1596 +0x43f
[24](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:24)
testing.(*M).Run(0xc000104180)
[25](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:25)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1504 +0x51d
[26](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:26)
main.main()
[27](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:27)
	_testmain.go:53 +0x14b
[28](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:28)

[29](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:29)
goroutine 23 [chan receive, 9 minutes]:
[30](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:30)
testing.(*B).doBench(0xc0000da6c0)
[31](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:31)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/benchmark.go:284 +0x8e
[32](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:32)
testing.(*B).run(0xc0000da6c0)
[33](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:33)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/benchmark.go:278 +0x6e
[34](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:34)
testing.Benchmark(0x12d0010)
[35](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:35)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/benchmark.go:818 +0xf9
[36](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:36)
github.com/tetratelabs/wazero/vs.TestFacIter_JIT_Fastest(0xc000001860)
[37](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:37)
	/home/runner/work/wazero/wazero/vs/bench_fac_iter_test.go:190 +0x215
[38](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:38)
testing.tRunner(0xc000001860, 0x12d0000)
[39](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:39)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1259 +0x102
[40](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:40)
created by testing.(*T).Run
[41](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:41)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1306 +0x35a
[42](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:42)

[43](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:43)
goroutine 28 [syscall, 9 minutes]:
[44](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:44)
github.com/birros/go-wasm3._Cfunc_m3_Call(0x7fbb3c08db90, 0x1, 0x4d082b0)
[45](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:45)
	_cgo_gotypes.go:478 +0x4d
[46](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:46)
github.com/birros/go-wasm3.(*Function).Call.func1(0x8, 0x1, 0x1)
[47](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:47)
	/home/runner/go/pkg/mod/github.com/birros/go-wasm3@v0.0.0-20220320175540-c625eebef38c/function.go:65 +0x73
[48](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:48)
github.com/birros/go-wasm3.(*Function).Call(0xc00000e048, {0xc00053c010, 0x1, 0x12cfe98})
[49](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:49)
	/home/runner/go/pkg/mod/github.com/birros/go-wasm3@v0.0.0-20220320175540-c625eebef38c/function.go:65 +0xce
[50](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:50)
github.com/tetratelabs/wazero/vs.goWasm3FacIterInvoke(0xc0000da6c0)
[51](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:51)
	/home/runner/work/wazero/wazero/vs/bench_fac_iter_test.go:293 +0xfd
[52](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:52)
testing.(*B).runN(0xc0000da6c0, 0x13e655)
[53](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:53)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/benchmark.go:192 +0x126
[54](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:54)
testing.(*B).launch(0xc0000da6c0)
[55](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:55)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/benchmark.go:328 +0x1c5
[56](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:56)
created by testing.(*B).doBench
[57](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:57)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/benchmark.go:283 +0x7b
[58](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:58)
exit status 2
[59](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:59)
FAIL	github.com/tetratelabs/wazero/vs	[60](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:60)0.014s
60
FAIL
[61](https://github.com/tetratelabs/wazero/runs/5706611192?check_suite_focus=true#step:5:61)
make: *** [Makefile:11: bench.check] Error 1
```

**Comment by mathetake** [comment]
I think this can be closed as we've removed the wasm3 target
