### ISSUE TITLE
various panics in JIT tests

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#435]
do any of these look fixable?

windows: https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true
```
Exception 0xc0000005 0x0 0x10 0x20b75380066
[25](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:25)
PC=0x20b75380066
[26](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:26)

[27](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:27)
runtime: unknown pc 0x20b75380066
[28](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:28)
stack: frame={sp:0xc0001cbb10, fp:0x0} stack=[0xc0001c4000,0xc0001cc000)
[29](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:29)
0x000000c0001cba10:  0x0000000000000000  0x000000c0001bf388 
[30](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:30)
0x000000c0001cba20:  0x0000000000000004  0x0000020b6fd1a430 
[31](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:31)
0x000000c0001cba30:  0x0000020b6fd18b2c  0x000000c0001cba28 
[32](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:32)
0x000000c0001cba40:  0x000000c0001cbbb8  0x0000000000d7514f <github.com/tetratelabs/wazero/internal/wasm/jit.(*engine).NewModuleEngine+0x00000000000004cf> 
[33](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:33)
0x000000c0001cba50:  0x0000000000000020  0x0000000002030000 
[34](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:34)
0x000000c0001cba60:  0x0000000000000020  0x0000000002030000 
[35](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:35)
0x000000c0001cba70:  0x0000000000030000  0x000000c000116580 
[36](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:36)
0x000000c0001cba80:  0x000000c0001cbaf8  0x0000000000ea49a8 
[37](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:37)
0x000000c0001cba90:  0x000000026fd1e670  0x0000020b6fd18b2c 
[38](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:38)
0x000000c0001cbaa0:  0x0000020b6fd18b2c  0x0000000000000000 
[39](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:39)
0x000000c0001cbab0:  0x0000000000b66555 <runtime.systemstack+0x0000000000000035>  0x0000000000b5e898 <runtime.callers+0x0000000000000098> 
[40](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:40)
0x000000c0001cbac0:  0x000000c0001cbad0  0x000000c0001cbb40 
[41](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:41)
0x000000c0001cbad0:  0x0000000000b0d785 <runtime.mallocgc+0x00000000000006c5>  0x0000000000bda131 <testing.(*common).Helper+0x00000000000000b1> 
[42](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:42)
0x000000c0001cbae0:  0x00000000000000b0  0x0000000000000200 
[43](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:43)
0x000000c0001cbaf0:  0x0000000000000002  0x000000c0001cbb50 
[44](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:44)
0x000000c0001cbb00:  0x0000020b6fcbae98  0x0000000000000098 
[45](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:45)
0x000000c0001cbb10: <0x0000000000d768c5 <github.com/tetratelabs/wazero/internal/wasm/jit.(*callEngine).execWasmFunction+0x0000000000000165>  0x0000020b75390000 
[46](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:46)
0x000000c0001cbb20:  0x000000c000116580  0x000000c000116580 
[47](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:47)
0x000000c0001cbb30:  0x0000000000000000  0x0000000000000008 
[48](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:48)
0x000000c0001cbb40:  0x000000c0001cbb68  0x0000000000b0dae7 <runtime.newobject+0x0000000000000027> 
[49](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:49)
0x000000c0001cbb[50](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:50):  0x00000000000000a8  0x0000000000e0fc80 
50
0x000000c0001cbb60:  0x0000000000e1b801  0x000000c0001cbbb0 
[51](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:51)
0x000000c0001cbb70:  0x0000000000d761a5 <github.com/tetratelabs/wazero/internal/wasm/jit.(*moduleEngine).newCallEngine+0x0000000000000085>  0x000000c000116610 
[52](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:52)
0x000000c0001cbb80:  0x0000020b6ff81308  0x000000c00013dd40 
[53](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:53)
0x000000c0001cbb90:  0x000000c000116580  0x0000000000000040 
[54](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:54)
0x000000c0001cbba0:  0x000000c000148600  0x000000c000164600 
[55](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:55)
0x000000c0001cbbb0:  0x000000c0001cbca0  0x0000000000d75bb6 <github.com/tetratelabs/wazero/internal/wasm/jit.(*moduleEngine).Call+0x00000000000003b6> 
[56](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:56)
0x000000c0001cbbc0:  0x000000c000116580  0x000000c00004d4c0 
[57](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:57)
0x000000c0001cbbd0:  0x0000020b6fd126a6  0x0000020b6fd126a6 
[58](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:58)
0x000000c0001cbbe0:  0x0000000000000000  0x010000c0001cbc20 
[59](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:59)
0x000000c0001cbbf0:  0x0000000000b14045 <runtime.typedmemmove+0x0000000000000065>  0x000000c0001cbc20 
[60](https://github.com/tetratelabs/wazero/runs/5805662242?check_suite_focus=true#step:5:60)
0x000000c0001cbc00:  0x000000c0001cbc78  0x0000000000b0d785 <runtime.mallocgc+0x00000000000006c5>
```

arm64 scratch: https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true
```
SIGILL: illegal instruction
[11](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:11)
PC=0x0 m=0 sigcode=2
[12](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:12)
instruction bytes: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
[13](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:13)

[14](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:14)
goroutine 22 [running]:
[15](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:15)
github.com/tetratelabs/wazero/internal/wasm/jit.(*moduleEngine).Call(0x38, 0x2f10e0, 0x40000a84c0, {0x1d401, 0x100010100009c88, 0x550100b4c0})
[16](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:16)
	/home/runner/work/wazero/wazero/internal/wasm/jit/engine.go:512 +0x314 fp=0x4000039be0 sp=0x4000039b10 pc=0x261274
[17](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:17)
runtime: unexpected return pc for github.com/tetratelabs/wazero/internal/wasm/jit.(*moduleEngine).Call called from 0x40
[18](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:18)
stack: frame={sp:0x4000039be0, fp:0x4000039cb0} stack=[0x4000038000,0x400003a000)
[19](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:19)
0x0000004000039ae0:  0x00000000000000c0  0x00000055010025b8 
[20](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:20)
0x0000004000039af0:  0x00000000000000c0  0x000000000056c2a0 
[21](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:21)
0x0000004000039b00:  0x0000004000124b40  0x0000004000039bb8 
[22](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:22)
0x0000004000039b10:  0x0000000000261274 <github.com/tetratelabs/wazero/internal/wasm/jit.(*moduleEngine).Call+0x0000000000000314>  0x0000005527ed7000 
[23](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:23)
0x0000004000039b20:  0x00000040001[24](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:24)b40  0x00000000000000c0 
24
0x0000004000039b30:  0x00000000002f62a0  0x0000004000039d01 
[25](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:25)
0x0000004000039b40:  0x0000004000124b40  0x0000004000039bb8 
[26](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:26)
0x0000004000039b50:  0x0000000000260ff0 <github.com/tetratelabs/wazero/internal/wasm/jit.(*moduleEngine).Call+0x0000000000000090>  0x00000000002f62a0 
[27](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:27)
0x0000004000039b60:  0x0000004000124b40  0x8000000000000000 
[28](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:28)
0x0000004000039b70:  0x0000004000159a00  0x0000004000094040 
[29](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:29)
0x0000004000039b80:  0x0000004000124be8  0x8000000000000000 
[30](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:30)
0x0000004000039b90:  0x0000000000000000  0x0000004000124b40 
[31](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:31)
0x0000004000039ba0:  0x0000000000000040  0x0000004000159a00 
[32](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:32)
0x0000004000039bb0:  0x0000004000080400  0x0000004000039c88 
[33](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:33)
0x0000004000039bc0:  0x000000000025ea60 <github.com/tetratelabs/wazero/internal/testing/enginetest.RunTestModuleEngine_Call_HostFn+0x0000000000000510>  0x0000004000124b40 
[34](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:34)
0x0000004000039bd0:  0x00000040000a8680  0x00000040000903c0 
[35](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:35)
0x0000004000039be0: <0x0000000000000040  0x0000000000000038 
[36](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:36)
0x0000004000039bf0:  0x00000000002f10e0  0x00000040000a84c0 
[37](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:37)
0x0000004000039c00:  0x000000000001d401 <runtime.(*hmap).newoverflow+0x0000000000000281>  0x0100010100009c88 
[38](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:38)
0x00000040000[39](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:39)c10:  0x000000550100b4c0  0x0000000000000000 
39
0x000000[40](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:40)00039c20:  0x0000000000000008  0x00000055010025b8 
40
0x0000004000039c30:  0x00000040000903c0  0x0000004000124b40 
[41](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:41)
0x0000004000039c40:  0x00000040000152e0  0x0000000000000000 
[42](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:42)
0x0000004000039c50:  0x0000004000039e28  0x0000004000039c88 
[43](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:43)
0x0000004000039c60:  0x00000040000903c0  0x0000004000124b40 
[44](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:44)
0x0000004000039c70:  0x00000040000a85c0  0x0000004000039ce0 
[45](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:45)
0x0000004000039c80:  0x000000000032bb78  0x0000004000025738 
[46](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:46)
[47](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:47)
0x0000004000039ca0:  0x00000040000a8680  0x00000040000b65b0 
[48](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:48)
0x0000004000039cb0: >0x00000040000152e0  0x0000000000000001 
[49](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:49)
0x0000004000039cc0:  0x0000000000000001  0x0000000000000000 
[50](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:50)
0x0000004000039cd0:  0x0000000000000000  0x0000000000000000 
[51](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:51)
0x0000004000039ce0:  0x0000000000000000  0x0000000000000000 
[52](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:52)
0x0000004000039cf0:  0x03000000000df618  0x0000000000000000 
[53](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:53)
0x0000004000039d00:  0x00000000004fb340  0x000000000037d108 
[54](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:54)
0x0000004000039d10:  0x000000000037d108  0x00000040000a8680 
[55](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:55)
0x0000004000039d20:  0x0000000000000039  0x0000004000178cf0 
[56](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:56)
0x0000004000039d30:  0x00000040000a85c0  0x0000004000178cf0 
[57](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:57)
0x0000004000039d40:  0x00000040000a84c0  0x0000004000178bd0 
[58](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:58)
0x0000004000039d50:  0x00000040000b65b0  0x0000004000014020 
[59](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:59)
0x0000004000039d[60](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:60):  0x00000040000b65b0  0x00000040000a85c0 
60
0x0000004000039d70:  0x000000000037d108  0x000000000037d108 
[61](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:61)
0x0000004000039d80:  0x00000040000a84c0  0x000000000037d108 
[62](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:62)
0x0000004000039d90:  0x00000040000a85c0  0x0000000000000002 
[63](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:63)
0x0000004000039da0:  0x8dd840de00000003  0x0000004000039e28 
[64](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:64)
github.com/tetratelabs/wazero/internal/wasm/jit.(*moduleEngine).Call(0x1, 0x1, 0x0, {0x0, 0x0, 0x0})
[65](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:65)
	/home/runner/work/wazero/wazero/internal/wasm/jit/engine.go:512 +0x314 fp=0x4000039cb0 sp=0x4000039be0 pc=0x261274
[66](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:66)
created by testing.(*T).Run
[67](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:67)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1306 +0x350
[68](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:68)

[69](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:69)
goroutine 1 [chan receive]:
[70](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:70)
testing.(*T).Run(0x400015e340, {0x31d582, 0x20}, 0x32bf98)
[71](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:71)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1307 +0x36c
[72](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:72)
testing.runTests.func1(0x400015e340)
[73](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:73)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1598 +0x80
[74](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:74)
testing.tRunner(0x400015e340, 0x4000107ca8)
[75](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:75)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1259 +0xf8
[76](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:76)
testing.runTests(0x400000c378, {0x534780, 0x3b, 0x3b}, {0x0, 0x0, 0x0})
[77](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:77)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1596 +0x3f8
[78](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:78)
testing.(*M).Run(0x400007e180)
[79](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:79)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1504 +0x510
[80](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:80)
github.com/tetratelabs/wazero/internal/wasm/jit.TestMain(0x400007e180)
[81](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:81)
	/home/runner/work/wazero/wazero/internal/wasm/jit/jit_test.go:21 +0x28
[82](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:82)
main.main()
[83](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:83)
	_testmain.go:161 +0x190
[84](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:84)

[85](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:85)
r0      0x4000124b40
[86](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:86)
r1      0x4000080408
[87](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:87)
r2      0x4000124be8
[88](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:88)
r3      0x1
[89](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:89)
r4      0x2
[90](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:90)
r5      0x4000159a40
[91](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:91)
r6      0x0
[92](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:92)
r7      0x2
[93](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:93)
r8      0x0
[94](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:94)
r9      0x0
[95](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:95)
r10     0x1000
[96](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:96)
r11     0x374504
[97](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:97)
r12     0xf2
[98](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:98)
r13     0x0
[99](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:99)
r14     0x0
[100](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:100)
r15     0x0
[101](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:101)
r16     0x18
[102](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:102)
r17     0x18
[103](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:103)
r18     0x0
[104](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:104)
r19     0x0
[105](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:105)
r20     0x4000039c78
[106](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:106)
r21     0x4dde38
[107](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:107)
r22     0x4dde00
[108](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:108)
r23     0x8
[109](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:109)
r24     0xffffffffffffffa2
[110](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:110)
r25     0x2cad00
[111](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:111)
r26     0x32c038
[112](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:112)
r27     0x5ab280
[113](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:113)
r28     0x400015e9c0
[114](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:114)
r29     0x4000039b08
[115](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:115)
lr      0x261f54
[116](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:116)
sp      0x4000039b10
[117](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:117)
pc      0x0
[118](https://github.com/tetratelabs/wazero/runs/5805662277?check_suite_focus=true#step:8:118)
fault   0x0
```

**Comment by mathetake** [comment]
I believe this is fixed
