### ISSUE TITLE
flakey test: gojs Test_stdio_large

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#992]
```
--- FAIL: Test_stdio_large (0.50s)
[34](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:35)
    require.go:312: expected "stderr 2097152
[35](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:36)
        ", but was "fatal error: malloc deadlock
[36](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:37)
        
[37](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:38)
        runtime stack:
[38](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:39)
        runtime.throw({0x6b9ce, 0xf})
[39](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:40)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/panic.go:1198 +0x7
[40](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:41)
        runtime.mallocgc(0x10, 0x42cc0, 0x1)
[41](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:42)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:972 +0xcf
[42](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:43)
        runtime.newobject(0x42cc0)
[43](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:44)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:1234 +0x4
[44](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:45)
        runtime.handleEvent()
[45](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:46)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/lock_js.go:238 +0x2
[46](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:47)
        runtime.sysReserve(0x0, 0x800000)
[47](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:48)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mem_js.go:68 +0xe
[48](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:49)
        runtime.sysReserveAligned(0x0, 0x400000, 0x400000)
[49](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:50)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:805 +0x2
[50](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:51)
        runtime.(*mheap).sysAlloc(0x329700, 0x400000)
[51](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:52)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:698 +0x4f
[52](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:53)
        runtime.(*mheap).grow(0x329700, 0x122)
[53](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:54)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:1347 +0xa
[54](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:55)
        runtime.(*mheap).allocSpan(0x329700, 0x122, 0x0, 0x1)
[55](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:56)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:1179 +0x3b
[56](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:57)
        runtime.(*mheap).alloc.func1()
[57](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:58)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:913 +0x6
[58](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:59)
        runtime.systemstack()
[59](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:60)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:170 +0x2
[60](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:61)
        runtime.mstart()
[61](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:62)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:28
[62](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:63)
        
[63](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:64)
        goroutine 1 [running]:
[64](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:65)
        runtime.systemstack_switch()
[65](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:66)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:181 fp=0x42ace8 sp=0x42ace0 pc=0x13ac0000
[66](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:67)
        runtime.(*mheap).alloc(0x329700, 0x122, 0x1, 0x0)
[67](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:68)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mheap.go:907 +0x2 fp=0x42ad30 sp=0x42ace8 pc=0x11750002
[68](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:69)
        runtime.(*mcache).allocLarge(0x350108, 0x244000, 0x0, 0x1)
[69](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:70)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/mcache.go:227 +0x9 fp=0x42ad90 sp=0x42ad30 pc=0x10ed0009
[70](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:71)
        runtime.mallocgc(0x244000, 0x0, 0x0)
[71](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:72)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/malloc.go:1088 +0x8f fp=0x42ae18 sp=0x42ad90 pc=0x10a4008f
[72](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:73)
        runtime.growslice(0x274c0, {0x500000, 0x1d0000, 0x1d0000}, 0x1d0001)
[73](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:74)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/slice.go:261 +0x83 fp=0x42ae68 sp=0x42ae18 pc=0x12c60083
[74](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:75)
        io.ReadAll({0xba820, 0x40c018})
[75](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:76)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/io/io.go:631 +0x7 fp=0x42aee0 sp=0x42ae68 pc=0x15530007
[76](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:77)
        github.com/tetratelabs/wazero/internal/gojs/testdata/stdio.Main()
[77](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:78)
        	/home/runner/work/wazero/wazero/internal/gojs/testdata/stdio/main.go:10 +0x2 fp=0x42af28 sp=0x42aee0 pc=0x1f2f0002
[78](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:79)
        main.main()
[79](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:80)
        	/home/runner/work/wazero/wazero/internal/gojs/testdata/main.go:40 +0x2a fp=0x42af88 sp=0x42af28 pc=0x1f34002a
[80](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:81)
        runtime.main()
[81](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:82)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/proc.go:255 +0x35 fp=0x42afe0 sp=0x42af88 pc=0x121f0035
[82](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:83)
        runtime.goexit()
[83](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:84)
        	/opt/hostedtoolcache/go/1.17.13/x64/src/runtime/asm_wasm.s:431 +0x1 fp=0x42afe8 sp=0x42afe0 pc=0x13d50001
[84](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:85)
        stderr 2097152
[85](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:86)
        "
[86](https://github.com/tetratelabs/wazero/actions/runs/3811321496/jobs/6483930063#step:4:87)
        /home/runner/work/wazero/wazero/internal/gojs/misc_test.go:56
```

**Comment by mathetake** [comment]
realized that this is not platform specific: just noticed this happened on amd64 as well https://github.com/tetratelabs/wazero/actions/runs/3826357387/jobs/6510080281

**Comment by mathetake** [comment]
this only happens with Go 1.17 as far as I can find in the Ci logs

**Comment by codefromthecrypt** [comment]
so maybe "saved by the bell" in the month or two when we drop 1.17 ;)

**Comment by mathetake** [comment]
seems like there's a race https://github.com/tetratelabs/wazero/actions/runs/3889335863/jobs/6637510795

**Comment by codefromthecrypt** [comment]
thanks for re-opening with an example failure. It looks like this has to do with the goroutine handling timeout events. We could handle this in a couple ways.. one is to try to fix the concurrency issue, knowing wasm isn't concurrent anyway. Another is to switch the timeout handler to a work stealing approach instead.

An example of work stealing could be to insert code inside `gojs.valueCall` to do this check and do any event handling prior to proceeding with the real call. Since none of this wasm is concurrent safe anyway, I think maybe it is the better idea and still allows the one scheduling a timeout event to defer it. @achille-roussel are you interested in trying this? If not, no biggie I will try to sort it next week after that.us conference

```
WARNING: DATA RACE
Write at 0x00c0081b8cd0 by goroutine 21:
  github.com/tetratelabs/wazero/internal/sys.(*FSContext).Close()
      /home/runner/work/wazero/wazero/internal/sys/fs.go:315 +0x73
  github.com/tetratelabs/wazero/internal/wasm.(*CallContext).close()
      /home/runner/work/wazero/wazero/internal/wasm/call_context.go:118 +0xb0
  github.com/tetratelabs/wazero/internal/wasm.(*CallContext).CloseWithExitCode()
      /home/runner/work/wazero/wazero/internal/wasm/call_context.go:94 +0x4c
  github.com/tetratelabs/wazero/internal/gojs.wasmExit()
      /home/runner/work/wazero/wazero/internal/gojs/runtime.go:29 +0xad
  github.com/tetratelabs/wazero/internal/gojs/goarch.(*stackFunc).Call()
      /home/runner/work/wazero/wazero/internal/gojs/goarch/wasm.go:172 +0x13a
  github.com/tetratelabs/wazero/internal/gojs/goarch.(*stackFunc).Call-fm()
      /home/runner/work/wazero/wazero/internal/gojs/goarch/wasm.go:170 +0x97
  github.com/tetratelabs/wazero/api.GoModuleFunc.Call()
      /home/runner/work/wazero/wazero/api/wasm.go:375 +0x82
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:924 +0x105d
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:669 +0x1e4
  github.com/tetratelabs/wazero/internal/wasm.(*function).Call()
      /home/runner/work/wazero/wazero/internal/wasm/call_context.go:209 +0x102
  github.com/tetratelabs/wazero/internal/gojs/run.RunAndReturnState()
      /home/runner/work/wazero/wazero/internal/gojs/run/gojs.go:32 +0x2fe
  github.com/tetratelabs/wazero/internal/gojs_test.compileAndRunWithRuntime()
      /home/runner/work/wazero/wazero/internal/gojs/compiler_test.go:45 +0x3e9
  github.com/tetratelabs/wazero/internal/gojs_test.compileAndRun()
      /home/runner/work/wazero/wazero/internal/gojs/compiler_test.go:27 +0x1a4
  github.com/tetratelabs/wazero/internal/gojs_test.Test_stdio_large()
      /home/runner/work/wazero/wazero/internal/gojs/misc_test.go:52 +0x20d
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x47

Previous read at 0x00c0081b8cd0 by goroutine 27:
  github.com/tetratelabs/wazero/internal/sys.(*FileTable).Lookup()
      /home/runner/work/wazero/wazero/internal/sys/file_table.go:88 +0x86
  github.com/tetratelabs/wazero/internal/sys.(*FSContext).LookupFile()
      /home/runner/work/wazero/wazero/internal/sys/fs.go:290 +0x2b
  github.com/tetratelabs/wazero/internal/sys.WriterForFile()
      /home/runner/work/wazero/wazero/internal/sys/fs.go:322 +0x141
  github.com/tetratelabs/wazero/internal/gojs.wasmWrite()
      /home/runner/work/wazero/wazero/internal/gojs/runtime.go:43 +0x118
  github.com/tetratelabs/wazero/internal/gojs/goarch.(*stackFunc).Call()
      /home/runner/work/wazero/wazero/internal/gojs/goarch/wasm.go:172 +0x13a
  github.com/tetratelabs/wazero/internal/gojs/goarch.(*stackFunc).Call-fm()
      /home/runner/work/wazero/wazero/internal/gojs/goarch/wasm.go:170 +0x97
  github.com/tetratelabs/wazero/api.GoModuleFunc.Call()
      /home/runner/work/wazero/wazero/api/wasm.go:375 +0x82
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:924 +0x105d
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:669 +0x1e4
  github.com/tetratelabs/wazero/internal/wasm.(*function).Call()
      /home/runner/work/wazero/wazero/internal/wasm/call_context.go:209 +0x102
  github.com/tetratelabs/wazero/internal/gojs.scheduleTimeoutEvent.func1()
      /home/runner/work/wazero/wazero/internal/gojs/runtime.go:113 +0x14e

Goroutine 21 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1504 +0x9d1
  github.com/tetratelabs/wazero/internal/gojs_test.TestMain()
      /home/runner/work/wazero/wazero/internal/gojs/compiler_test.go:113 +0x610
  main.main()
      _testmain.go:71 +0x264

Goroutine 27 (running) created at:
  github.com/tetratelabs/wazero/internal/gojs.scheduleTimeoutEvent()
      /home/runner/work/wazero/wazero/internal/gojs/runtime.go:109 +0x27b
  github.com/tetratelabs/wazero/internal/gojs/goarch.(*stackFunc).Call()
      /home/runner/work/wazero/wazero/internal/gojs/goarch/wasm.go:172 +0x13a
  github.com/tetratelabs/wazero/internal/gojs/goarch.(*stackFunc).Call-fm()
      /home/runner/work/wazero/wazero/internal/gojs/goarch/wasm.go:170 +0x97
  github.com/tetratelabs/wazero/api.GoModuleFunc.Call()
      /home/runner/work/wazero/wazero/api/wasm.go:375 +0x82
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:924 +0x105d
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:669 +0x1e4
  github.com/tetratelabs/wazero/internal/wasm.(*function).Call()
      /home/runner/work/wazero/wazero/internal/wasm/call_context.go:209 +0x102
  github.com/tetratelabs/wazero/internal/gojs.funcWrapper.invoke()
      /home/runner/work/wazero/wazero/internal/gojs/syscall.go:431 +0x34e
  github.com/tetratelabs/wazero/internal/gojs.jsfsRead.invoke()
      /home/runner/work/wazero/wazero/internal/gojs/fs.go:265 +0x884
  github.com/tetratelabs/wazero/internal/gojs.(*jsfsRead).invoke()
      <autogenerated>:1 +0xa8
  github.com/tetratelabs/wazero/internal/gojs.(*jsVal).call()
      /home/runner/work/wazero/wazero/internal/gojs/js.go:68 +0x10a
  github.com/tetratelabs/wazero/internal/gojs.valueCall()
      /home/runner/work/wazero/wazero/internal/gojs/syscall.go:166 +0x1e6
  github.com/tetratelabs/wazero/internal/gojs/goos.(*stackFunc).Call()
      /home/runner/work/wazero/wazero/internal/gojs/goos/goos.go:248 +0x182
  github.com/tetratelabs/wazero/internal/gojs/goos.(*stackFunc).Call-fm()
      /home/runner/work/wazero/wazero/internal/gojs/goos/goos.go:246 +0x97
  github.com/tetratelabs/wazero/api.GoModuleFunc.Call()
      /home/runner/work/wazero/wazero/api/wasm.go:375 +0x82
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).execWasmFunction()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:924 +0x105d
  github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).Call()
      /home/runner/work/wazero/wazero/internal/engine/compiler/engine.go:669 +0x1e4
  github.com/tetratelabs/wazero/internal/wasm.(*function).Call()
      /home/runner/work/wazero/wazero/internal/wasm/call_context.go:209 +0x102
  github.com/tetratelabs/wazero/internal/gojs/run.RunAndReturnState()
      /home/runner/work/wazero/wazero/internal/gojs/run/gojs.go:32 +0x2fe
  github.com/tetratelabs/wazero/internal/gojs_test.compileAndRunWithRuntime()
      /home/runner/work/wazero/wazero/internal/gojs/compiler_test.go:45 +0x3e9
  github.com/tetratelabs/wazero/internal/gojs_test.compileAndRun()
      /home/runner/work/wazero/wazero/internal/gojs/compiler_test.go:27 +0x1a4
  github.com/tetratelabs/wazero/internal/gojs_test.Test_stdio_large()
      /home/runner/work/wazero/wazero/internal/gojs/misc_test.go:52 +0x20d
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1306 +0x47
```
